name: Deploy test

on:
push:
branches:
-master

jobs:

create-deployment artifacts
name: Test create deploy
runs-on:ubuntu-latest
-steps: actions/checkout@v2
-name:Compile CSS and javascript
run:
npm install
npm run prod